// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageWebAppWertz.Models;

namespace MultiPageWebAppWertz.Migrations
{
    [DbContext(typeof(PhoneContext))]
    [Migration("20210217070101_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultiPageWebAppWertz.Models.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PNumber")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("PhoneId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            PhoneId = 1,
                            Address = "708 26th St SE",
                            Name = "Isaiah Wertz",
                            Note = "It's me",
                            PNumber = 5157770852L
                        },
                        new
                        {
                            PhoneId = 2,
                            Address = "708 26th St SE",
                            Name = "Shannon Hodges",
                            Note = "It's my mom",
                            PNumber = 5158224692L
                        },
                        new
                        {
                            PhoneId = 3,
                            Address = "Null",
                            Name = "John Doe",
                            Note = "It's a fake",
                            PNumber = 5155555555L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
